# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Question.create(question: "Why are you studying a foreign language?")
# Question.create(question: "What are your favorite hobbies?")
# Question.create(question: "Describe yourself using three words")
# Question.create(question: "What are your favorite hobbies?")
# Question.create(question: "What is one goal you’d like to accomplish during your lifetime?")
Question.create(question: "If you could have an endless supply of any food, what would you get?")
Question.create(question: "If you were an animal, what would you be and why?")
Question.create(question: "Who is your hero? (a parent, a celebrity, an influential person in one’s life)")
Question.create(question: "What’s your favorite thing to do in the summer?")
Question.create(question: "If they made a movie of your life, what would it be about and which actor would you want to play you?")
Question.create(question: "If you were an ice cream flavor, which one would you be and why?")
Question.create(question: "What’s your favorite cartoon character, and why?")
Question.create(question: "If you could visit any place in the world, where would you choose to go and why?")
Question.create(question: "What’s the ideal dream job for you?")
Question.create(question: "Are you a morning or night person?")
Question.create(question: "What are your pet peeves or interesting things about you that you dislike?")
Question.create(question: "What’s the weirdest thing you’ve ever eaten?")
Question.create(question: "Name one of your favorite things about someone in your family.")
Question.create(question: "Tell us about a unique or quirky habit of yours.")
Question.create(question: "If someone made a movie of your life would it be a drama, a comedy, a romantic-comedy, action film, or science fiction?")
Question.create(question: "If you were a vegetable, what vegetable would you be?")
Question.create(question: "If you woke up tomorrow as an animal, what animal would you choose to be and why?")
Question.create(question: "Do you prefer sunrise, daylight, twilight, or night?")
Question.create(question: "If you could choose one age forever, what age would you choose and why?")
Question.create(question: "If you could be in the movie of your choice, what movie would you choose and what character would you play?")
Question.create(question: "If you could meet any historical figure, who would you choose and why?")
Question.create(question: "What is your favorite city?")
Question.create(question: "What is your favorite candy bar?")
Question.create(question: "If you were to change your name, what name would you choose and why?")
Question.create(question: "Do you prefer spring, summer, fall, or winter? Why?")
Question.create(question: "If you were stranded on a desert island, what three items would you want to have with you?")
Question.create(question: "If you could only choose one vacation destination where would you pick and why?")
Question.create(question: "If you were to create a slogan for your life, what would it be? (Example: Eat, drink, and be merry, for tomorrow, we all die.)")
Question.create(question: "Name one thing in your pocket, bag or purse and share what it is, and why you have it.")
Question.create(question: "What is your best feature?")
Question.create(question: "What’s the best thing that’s happened to you this week?")
Question.create(question: "Who was your role model when you were a child?")
Question.create(question: "Who was your favorite teacher and why?")
Question.create(question: "What was your favorite subject at school?")
Question.create(question: "What would be your perfect job?")
Question.create(question: "What is your greatest achievement?")
Question.create(question: "Have you ever won a trophy or medal?")
Question.create(question: "What is the longest word you know?")
Question.create(question: "Who is the most inspirational person to you?")
Question.create(question: "If you could have one wish come true what would it be?")
Question.create(question: "Did you ever keep a New Year’s resolution?")
Question.create(question: "What was your favorite birthday or Christmas present?")
Question.create(question: "What was the worst present you’ve received?")
Question.create(question: "What was your favorite childhood toy?")
Question.create(question: "Where would you like to be in five years time?")
Question.create(question: "Which skill would you love to learn?")
Question.create(question: "What other language would you like to learn?")
Question.create(question: "If money was not a concern what would you do every day if you didn’t work?")
Question.create(question: "What’s your hidden talent?")
Question.create(question: "What was the funniest moment in your life?")
Question.create(question: "What was the most embarrassing moment in your life?")
Question.create(question: "Have you seen a ghost or an alien?")
Question.create(question: "Do you believe in ghosts?")
Question.create(question: "Do you believe in aliens?")
Question.create(question: "Would you like to see into the future? Why?")
Question.create(question: "Would you like to be invisible for a day? Why?")
Question.create(question: "If you could rule the world for a day state something that you’d ban.")
Question.create(question: "If you had magical powers name something that you’d change.")
Question.create(question: "What irritates you the most?")
Question.create(question: "Where would you most like to live?")
Question.create(question: "If you were a flower which one would you be?")
Question.create(question: "Which animal would you choose to be?")
Question.create(question: "What is your favorite food?")
Question.create(question: "What is your favorite drink?")
Question.create(question: "Which task or chore is least favorite?")
Question.create(question: "What type of car is your favorite?")
Question.create(question: "Did you ever lock your car keys in the car?")
Question.create(question: "What is your favorite TV show and why?")
Question.create(question: "What is your favorite song?")
Question.create(question: "What is your favorite book?")
Question.create(question: "What is your favorite film?")
Question.create(question: "Who would you like to be for a day?")
Question.create(question: "Who would play you in a film?")
Question.create(question: "Which famous person would you like to meet?")
Question.create(question: "Which famous person would you never want to meet?")
Question.create(question: "If you could invite five famous or noted people (past or present) to dinner who would you choose?")
Question.create(question: "Which time period would you visit in history?")
Question.create(question: "Do you have any brothers or sisters?")
Question.create(question: "Where did you grow up?")
Question.create(question: "What is your favorite thing you own?")
Question.create(question: "Do you like to workout?")
Question.create(question: "What technology innovation made the most impact on your life?")
Question.create(question: "How would you spend one million dollars?")
Question.create(question: "What is your earliest childhood memory.")
Question.create(question: "What is one important skill every person should have? ")
Question.create(question: "Do you watch sports? If so, which is your favorite?")
Question.create(question: "If you had one free hour each day, how would you use it? ")
Question.create(question: "What is the craziest thing you've ever done?")
Question.create(question: "What’s your middle name?")
Question.create(question: "What was the first car you owned?")
Question.create(question: "How many siblings do you have and what are their names?")
Question.create(question: "If you could pick another eye color for yourself, which color would you choose?")
Question.create(question: "What’s your favorite holiday?")
Question.create(question: "Do you have any scars? If so, what are they from?")
Question.create(question: "Do you have a birthmark?")
Question.create(question: "What’s your profession?")
Question.create(question: "What was your first pet’s name?")
Question.create(question: "What’s your genetic heritage?")
Question.create(question: "What’s your astrological sign?")
Question.create(question: "What is one of your goals for this year?")
Question.create(question: "If you could live one day over again, what day would you pick?")
Question.create(question: "If you were sent to live on a space station for three months and allowed to bring only one personal item with you, what would it be?")
Question.create(question: "What is one nickname you have?")
Question.create(question: "If you knew you couldn’t fail, what would you do?")
Question.create(question: "If you were a teacher, what would you teach?")
Question.create(question: "What’s the worst job you’ve ever had?")
Question.create(question: "What’s the scariest thing you’ve ever done?")
Question.create(question: "You’re stranded on a desert island for a year. Would you rather be alone or with someone you don’t like?")
Question.create(question: "What is your favorite thing to do on a rainy day?")
Question.create(question: "What was one fun thing you did last weekend?")
Question.create(question: "Do you have any tattoos? If so, what are they?")
Question.create(question: "If you had a time machine for the weekend, where would you go?")
Question.create(question: "Where did you last vacation?")
Question.create(question: "What’s your favorite town/city in the world?")
Question.create(question: "Where do you hope to live when you retire?")
Question.create(question: "If you had 10 million dollars, how would you spend it?")
Question.create(question: "Do you play any instruments?")
Question.create(question: "What is your favorite thing to do outside?")
Question.create(question: "If you could observe any animal in its natural habitat, what would you choose?")
Question.create(question: "If you could tame one wild animal to be your companion, what animal would you choose?")
Question.create(question: "What was the last book you read?")
Question.create(question: "What’s your favorite book?")
Question.create(question: "What’s your favorite mythical creature?")
Question.create(question: "Who is the most famous person you’ve seen or met in person.")
Question.create(question: "What was the first live concert you ever attended?")
Question.create(question: "What was the first record or cd that you bought?")
Question.create(question: "What’s your favorite food?")
Question.create(question: "What was the last thing you ate?")
Question.create(question: "What’s your favorite unusual food combination?")
Question.create(question: "What is your favorite fruit?")
Question.create(question: "What are your favorite pizza toppings?")
Question.create(question: "What do you usually do on a Friday night?")










