# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Question.create(question: "Why are you studying a foreign language?")
# Question.create(question: "What are your favorite hobbies?")
# Question.create(question: "Describe yourself using three words")
# Question.create(question: "What are your favorite hobbies?")
# Question.create(question: "What is one goal you’d like to accomplish during your lifetime?")
# Question.create(question: "If you could have an endless supply of any food, what would you get?")
# Question.create(question: "If you were an animal, what would you be and why?")
# Question.create(question: "Who is your hero? (a parent, a celebrity, an influential person in one’s life)")
# Question.create(question: "What’s your favorite thing to do in the summer?")
# Question.create(question: "If they made a movie of your life, what would it be about and which actor would you want to play you?")
# Question.create(question: "If you were an ice cream flavor, which one would you be and why?")
# Question.create(question: "What’s your favorite cartoon character, and why?")
# Question.create(question: "If you could visit any place in the world, where would you choose to go and why?")
# Question.create(question: "What’s the ideal dream job for you?")
# Question.create(question: "Are you a morning or night person?")
# Question.create(question: "What are your pet peeves or interesting things about you that you dislike?")
# Question.create(question: "What’s the weirdest thing you’ve ever eaten?")
# Question.create(question: "Name one of your favorite things about someone in your family.")
# Question.create(question: "Tell us about a unique or quirky habit of yours.")
# Question.create(question: "If someone made a movie of your life would it be a drama, a comedy, a romantic-comedy, action film, or science fiction?")
# Question.create(question: "If you were a vegetable, what vegetable would you be?")
# Question.create(question: "If you woke up tomorrow as an animal, what animal would you choose to be and why?")
# Question.create(question: "Do you prefer sunrise, daylight, twilight, or night?")
# Question.create(question: "If you could choose one age forever, what age would you choose and why?")
# Question.create(question: "If you could be in the movie of your choice, what movie would you choose and what character would you play?")
# Question.create(question: "If you could meet any historical figure, who would you choose and why?")
# Question.create(question: "What is your favorite city?")
# Question.create(question: "What is your favorite candy bar?")
# Question.create(question: "If you were to change your name, what name would you choose and why?")
# Question.create(question: "Do you prefer spring, summer, fall, or winter? Why?")
# Question.create(question: "If you were stranded on a desert island, what three items would you want to have with you?")
# Question.create(question: "If you could only choose one vacation destination where would you pick and why?")
# Question.create(question: "If you were to create a slogan for your life, what would it be? (Example: Eat, drink, and be merry, for tomorrow, we all die.)")
# Question.create(question: "Name one thing in your pocket, bag or purse and share what it is, and why you have it.")
# Question.create(question: "What is your best feature?")
# Question.create(question: "What’s the best thing that’s happened to you this week?")
# Question.create(question: "Who was your role model when you were a child?")
# Question.create(question: "Who was your favorite teacher and why?")
# Question.create(question: "What was your favorite subject at school?")
# Question.create(question: "What would be your perfect job?")
# Question.create(question: "What is your greatest achievement?")
# Question.create(question: "Have you ever won a trophy or medal?")
# Question.create(question: "What is the longest word you know?")
# Question.create(question: "Who is the most inspirational person to you?")
# Question.create(question: "If you could have one wish come true what would it be?")
# Question.create(question: "Did you ever keep a New Year’s resolution?")
# Question.create(question: "What was your favorite birthday or Christmas present?")
# Question.create(question: "What was the worst present you’ve received?")
# Question.create(question: "What was your favorite childhood toy?")
# Question.create(question: "Where would you like to be in five years time?")
# Question.create(question: "Which skill would you love to learn?")
# Question.create(question: "What other language would you like to learn?")
# Question.create(question: "If money was not a concern what would you do every day if you didn’t work?")
# Question.create(question: "What’s your hidden talent?")
# Question.create(question: "What was the funniest moment in your life?")
# Question.create(question: "What was the most embarrassing moment in your life?")
# Question.create(question: "Have you seen a ghost or an alien?")
# Question.create(question: "Do you believe in ghosts?")
# Question.create(question: "Do you believe in aliens?")
# Question.create(question: "Would you like to see into the future? Why?")
# Question.create(question: "Would you like to be invisible for a day? Why?")
# Question.create(question: "If you could rule the world for a day state something that you’d ban.")
# Question.create(question: "If you had magical powers name something that you’d change.")
# Question.create(question: "What irritates you the most?")
# Question.create(question: "Where would you most like to live?")
# Question.create(question: "If you were a flower which one would you be?")
# Question.create(question: "Which animal would you choose to be?")
# Question.create(question: "What is your favorite food?")
# Question.create(question: "What is your favorite drink?")
# Question.create(question: "Which task or chore is least favorite?")
# Question.create(question: "What type of car is your favorite?")
# Question.create(question: "Did you ever lock your car keys in the car?")
# Question.create(question: "What is your favorite TV show and why?")
# Question.create(question: "What is your favorite song?")
# Question.create(question: "What is your favorite book?")
# Question.create(question: "What is your favorite film?")
# Question.create(question: "Who would you like to be for a day?")
# Question.create(question: "Who would play you in a film?")
# Question.create(question: "Which famous person would you like to meet?")
# Question.create(question: "Which famous person would you never want to meet?")
# Question.create(question: "If you could invite five famous or noted people (past or present) to dinner who would you choose?")
# Question.create(question: "Which time period would you visit in history?")
# Question.create(question: "Do you have any brothers or sisters?")
# Question.create(question: "Where did you grow up?")
# Question.create(question: "What is your favorite thing you own?")
# Question.create(question: "Do you like to workout?")
# Question.create(question: "What technology innovation made the most impact on your life?")
# Question.create(question: "How would you spend one million dollars?")
# Question.create(question: "What is your earliest childhood memory.")
# Question.create(question: "What is one important skill every person should have? ")
# Question.create(question: "Do you watch sports? If so, which is your favorite?")
# Question.create(question: "If you had one free hour each day, how would you use it? ")
# Question.create(question: "What is the craziest thing you've ever done?")
# Question.create(question: "What’s your middle name?")
# Question.create(question: "What was the first car you owned?")
# Question.create(question: "How many siblings do you have and what are their names?")
# Question.create(question: "If you could pick another eye color for yourself, which color would you choose?")
# Question.create(question: "What’s your favorite holiday?")
# Question.create(question: "Do you have any scars? If so, what are they from?")
# Question.create(question: "Do you have a birthmark?")
# Question.create(question: "What’s your profession?")
# Question.create(question: "What was your first pet’s name?")
# Question.create(question: "What’s your genetic heritage?")
# Question.create(question: "What’s your astrological sign?")
# Question.create(question: "What is one of your goals for this year?")
# Question.create(question: "If you could live one day over again, what day would you pick?")
# Question.create(question: "If you were sent to live on a space station for three months and allowed to bring only one personal item with you, what would it be?")
# Question.create(question: "What is one nickname you have?")
# Question.create(question: "If you knew you couldn’t fail, what would you do?")
# Question.create(question: "If you were a teacher, what would you teach?")
# Question.create(question: "What’s the worst job you’ve ever had?")
# Question.create(question: "What’s the scariest thing you’ve ever done?")
# Question.create(question: "You’re stranded on a desert island for a year. Would you rather be alone or with someone you don’t like?")
# Question.create(question: "What is your favorite thing to do on a rainy day?")
# Question.create(question: "What was one fun thing you did last weekend?")
# Question.create(question: "Do you have any tattoos? If so, what are they?")
# Question.create(question: "If you had a time machine for the weekend, where would you go?")
# Question.create(question: "Where did you last vacation?")
# Question.create(question: "What’s your favorite town/city in the world?")
# Question.create(question: "Where do you hope to live when you retire?")
# Question.create(question: "If you had 10 million dollars, how would you spend it?")
# Question.create(question: "Do you play any instruments?")
# Question.create(question: "What is your favorite thing to do outside?")
# Question.create(question: "If you could observe any animal in its natural habitat, what would you choose?")
# Question.create(question: "If you could tame one wild animal to be your companion, what animal would you choose?")
# Question.create(question: "What was the last book you read?")
# Question.create(question: "What’s your favorite book?")
# Question.create(question: "What’s your favorite mythical creature?")
# Question.create(question: "Who is the most famous person you’ve seen or met in person.")
# Question.create(question: "What was the first live concert you ever attended?")
# Question.create(question: "What was the first record or cd that you bought?")
# Question.create(question: "What’s your favorite food?")
# Question.create(question: "What was the last thing you ate?")
# Question.create(question: "What’s your favorite unusual food combination?")
# Question.create(question: "What is your favorite fruit?")
# Question.create(question: "What are your favorite pizza toppings?")
# Question.create(question: "What do you usually do on a Friday night?")



# Animal.create(picture: "Pig", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTkkbcmQ3SlibVstRHrYEKGhk2-Fx9kt8-xYT5Gz7F8YU849xHryg")
# Animal.create(picture: "Horse", url: "http://www.horsechannel.com/images/horse-news-article-images/chestnut-horse-autumn_1000.jpg")
# Animal.create(picture: "Alligator", url: "http://cdn.images.express.co.uk/img/dynamic/78/590x/secondary/alligators-571014.jpg")
# Animal.create(picture: "Ant", url: "http://dreamicus.com/data/ant/ant-05.jpg")
# Animal.create(picture: "Bear", url: "http://static.boredpanda.com/blog/wp-content/uploads/2016/09/mother-bear-cubs-animal-parenting-21-57e3a2161d7f7__880.jpg")
# Animal.create(picture: "Bee", url: "http://yourshot.nationalgeographic.com/u/ss/fQYSUbVfts-T7pS2VP2wnKyN8wxywmXtY0-FwsgxpCrcJO9rnvc0MhB8vLF3_Hflr-DyKKgGeVcUxqDT1sVz/")
# Animal.create(picture: "Bird", url: "http://www.nature.org/cs/groups/webcontent/@web/@pennsylvania/documents/media/indigo-bunting-720x400.jpg")
# Animal.create(picture: "Butterfly", url: "https://s-media-cache-ak0.pinimg.com/736x/08/7d/7f/087d7f0069385dd543178c4c2fca3430.jpg")
# Animal.create(picture: "Cat", url: "http://www.popsci.com/sites/popsci.com/files/styles/large_1x_/public/images/2016/08/1200px-chat_des_sables_felis_margarita.jpeg?itok=ISrKp-wL&fc=50,50")
# Animal.create(picture: "Cheetah", url: "https://static1.squarespace.com/static/54f738bee4b08d5963bb05bf/t/54ff4f98e4b033cba9481ec6/1426018202405/ec6dae614acb.jpg?format=1500w")
# Animal.create(picture: "Chicken", url: "http://www.gourmetsleuth.com/images/default-source/articles/big-white-chicken.jpg?sfvrsn=8")
# Animal.create(picture: "Cow", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cow_female_black_white.jpg/1200px-Cow_female_black_white.jpg")
# Animal.create(picture: "Crocodile", url: "http://www.outback-australia-travel-secrets.com/image-files/crocodile-attacks-4.jpg")
# Animal.create(picture: "Deer", url: "http://www.hudson.oh.us/ImageRepository/Document?documentID=2585")
# Animal.create(picture: "Camel", url: "http://farm3.static.flickr.com/2619/4106977090_c56c14cab1.jpg")
# Animal.create(picture: "Dog", url: "https://cdn.pixabay.com/photo/2016/02/19/15/46/dog-1210559_960_720.jpg")
# Animal.create(picture: "Dolphin", url: "https://s-media-cache-ak0.pinimg.com/originals/a2/36/b5/a236b548637a9758bf8eb8fe666cc33a.jpg")
# Animal.create(picture: "Duck", url: "http://media-cdn.tripadvisor.com/media/photo-s/03/75/bf/56/wild-duck.jpg")
# Animal.create(picture: "Eagle", url: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Bald_Eagle_Head_2_(6021915997).jpg")
# Animal.create(picture: "Elephant", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7wkab4YNBu9jEBBMy47pZfp2DTfrFGgntUHgtgbrefaupQtMNbw")
# Animal.create(picture: "Fish", url: "https://s-media-cache-ak0.pinimg.com/736x/0b/25/34/0b2534091d482a4a2269bd65a972d7c5.jpg")
# Animal.create(picture: "Fly", url: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Pollenia-sp-Cluster-fly-20100718a.jpg")
# Animal.create(picture: "Fox", url: "https://s-media-cache-ak0.pinimg.com/originals/26/05/75/260575bf1fc0c380d2d2c3288564b30c.jpg")
# Animal.create(picture: "Frog", url: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSAgEMB0vHs_EgTVR82XSMR99GFxG4ShIxSabGzFEQfq7hJXoKn")
# Animal.create(picture: "Giraffe", url: "https://giraffeconservation.org/wp-content/uploads/2016/02/gcf-15-of-37.jpg")
# Animal.create(picture: "Goat", url: "http://cdn.images.express.co.uk/img/dynamic/78/590x/secondary/goat-523061.jpg")
# Animal.create(picture: "Goldfish", url: "http://sunlandwatergardens.com/wp-content/uploads/2013/06/Pond_fishGoldfishRed-FantailFantail-goldfishgoldfish-for-ponds.jpg")
# Animal.create(picture: "Hamster", url: "http://www.sciencemag.org/sites/default/files/styles/article_main_large/public/images/sn-hamster.jpg?itok=YkpKAYNJ")
# Animal.create(picture: "Hippopotamus", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPZbcjCh8JkvFjEI5UbmcfoQzWCrHJMhC1W3UfxCd1jJCZqacqeg")
# Animal.create(picture: "Kangaroo", url: "https://i.guim.co.uk/img/media/96179c5762e526e05ad68d35e1e4eb9b961b0422/640_1244_4112_2466/4112.jpg?w=460&q=55&auto=format&usm=12&fit=max&s=092fcdd2d342ebd3f7502666c72cbbe0")
# Animal.create(picture: "Kitten", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRYgLXuYrWDOjljZn8gAhpeVECuBUeFPAvSnHaV-sGke0dBVQxDjQ")
# Animal.create(picture: "Llama", url: "https://s-media-cache-ak0.pinimg.com/564x/b9/b1/45/b9b1453e7c64ee9ca2f3f8911f4401e9.jpg")
# Animal.create(picture: "Lion", url: "http://kids.nationalgeographic.com/content/dam/kids/photos/animals/Mammals/H-P/lion-male-roar.jpg.adapt.945.1.jpg")
# Animal.create(picture: "Lobster", url: "http://pngimg.com/uploads/lobster/lobster_PNG14262.png")
# Animal.create(picture: "Monkey", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSP9wyqCXkACSjAIOaWQvmTd7k1hP5247JDkzGXZ-fLiAz2Sca0Gw")
# Animal.create(picture: "Octopus", url: "http://pixel.nymag.com/imgs/daily/science/2016/12/19/19-octopus.w710.h473.2x.jpg")
# Animal.create(picture: "Owl", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_(1).jpg/170px-Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_(1).jpg")
# Animal.create(picture: "Panda", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhWKr2lSzPMQ6RCQ7Uvkk5DZu92ARP7mowxaHcMM1LABbK-rxC")
# Animal.create(picture: "Puppy", url: "http://animalfair.com/wp-content/uploads/2013/09/macexplorer.com-puppy-dog-26.jpg")
# Animal.create(picture: "Rabbit", url: "https://s-media-cache-ak0.pinimg.com/originals/df/1b/9f/df1b9fc4e0c6bd38cc5c716de4b9e8cb.jpg")
# Animal.create(picture: "Rat", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSeH2ztRiv2GKSdi32Uh8WM89_i8jy1tjeAeUa01GxvOS2Ol8PI")
# Animal.create(picture: "Scorpion", url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQA5ZooKyxskX6LLPmNdnQzjHWp4OsL553jf-JEt4ow7Fm2oyVI")
# Animal.create(picture: "Seal", url: "http://insider.si.edu/wordpress/wp-content/uploads/2014/05/CARIBBEAN-MONK-SEALRET2-630x410.jpg")
# Animal.create(picture: "Shark", url: "http://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2015/08/18/102930512-Great_white_shark.1910x1000.jpg")
# Animal.create(picture: "Sheep", url: "http://www.ravishly.com/sites/default/files/ThinkstockPhotos-182344013.jpg")
# Animal.create(picture: "Snail", url: "http://images2.onionstatic.com/clickhole/2184/4/16x9/800.jpg")
# Animal.create(picture: "Snake", url: "http://www.ecologyasia.com/images-pqr/paradise-tree-snake_3022.jpg")
# Animal.create(picture: "Spider", url: "http://www.livescience.com/images/i/000/079/136/original/bradford-green-magnolia.jpg?interpolation=lanczos-none&downsize=*:1000")
# Animal.create(picture: "Squirrel", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMkG3IA1-9fNn228VAbK164M3t8lxBry2Dz1UtqnDuw17nizAK")
# Animal.create(picture: "Swan", url: "http://www.coolkidfacts.com/wp-content/uploads/2015/03/elegant-swans.jpg")
# Animal.create(picture: "Tiger", url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ5iS3guFbUM6UDtaZ0w9XEG8UCCSMUweS8qNYl46zQfvG1R4zc7w")
# Animal.create(picture: "Turtle", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyqR2BQTS1_z96YvQq4tfi5q4rMu76WMM2rp10mI2QyCbQJoGZ")
# Animal.create(picture: "Unicorn", url: "http://i.huffpost.com/gen/2424200/images/o-UNICORN-facebook.jpg")
# Animal.create(picture: "Whale", url: "http://cdn.natgeotv.com.au/factsheets/thumbnails/UnderstandingTheBlueWhale_whale.jpg?v=18&azure=false&scale=both&width=1600&height=900&mode=crop")
# Animal.create(picture: "Wolf", url: "https://i.cbc.ca/1.3476516.1457118314!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_940/wolf-howling.jpg")
# Animal.create(picture: "Zebra", url: "https://gifts.worldwildlife.org/gift-center/Images/large-species-photo/large-Zebra-photo.jpg")


WouldYouRather.create(question: "Would you rather fight 1 horse-sized duck, or 100 duck-sized horses?")
WouldYouRather.create(question: "Which would you prefer — three wishes over five years or one wish right now?")
WouldYouRather.create(question: "Would you rather be clever or beautiful?")
WouldYouRather.create(question: "Would you rather be really hairy or bald?")
WouldYouRather.create(question: "Would you like to be taller or thinner?")
WouldYouRather.create(question: "Would you rather go to a tropical island or the Arctic")
WouldYouRather.create(question: "Would you rather be hot or cold?")
WouldYouRather.create(question: "Would you rather lock yourself out of your house or your car?")
WouldYouRather.create(question: "Would you rather have true love or $1 million?")
WouldYouRather.create(question: "Would you prefer to visit Earth in 2100 or travel back to 1900?")
WouldYouRather.create(question: "Would you rather have a dog or a cat?")
WouldYouRather.create(question: "Would you rather meet your ancestors or descendants?")
WouldYouRather.create(question: "Would you rather have the ability to be invisible or to read minds?")
WouldYouRather.create(question: "Would you rather be able to fly or breathe underwater?")
WouldYouRather.create(question: "Would you rather go on vacation to Europe or the Caribbean?")
WouldYouRather.create(question: "Would you rather legally change your last name to Hitler, or never eat chocolate again?")
WouldYouRather.create(question: "Would you rather have no internet, or no cell phone?")
WouldYouRather.create(question: "Would you rather have no one show up to your funeral or wedding?")
WouldYouRather.create(question: "Would you rather visit the doctor or the dentist?")
WouldYouRather.create(question: "Would you rather eat broccoli or carrots?")
WouldYouRather.create(question: "Would you rather be a giant rodent or a tiny elephant?")
WouldYouRather.create(question: "Would you rather watch TV or listen to music?")
WouldYouRather.create(question: "Would you rather own a lizard or a snake?")
WouldYouRather.create(question: "Would you rather have a beach holiday or a mountain holiday?")
WouldYouRather.create(question: "Would you rather be invisible or be able to read minds?")
WouldYouRather.create(question: "Would you rather be hairy all over or completely bald?")
WouldYouRather.create(question: "Would you rather be the most popular or the smartest person alive?")
WouldYouRather.create(question: "Would you rather make headlines for saving somebody’s life or winning a Nobel Prize?")
WouldYouRather.create(question: "Would you rather go without television or fast food for the rest of your life?")
WouldYouRather.create(question: "Would you rather be attractive and dumb or be ugly and really smart?")
WouldYouRather.create(question: "Would you rather always be cold or always be hot?")
WouldYouRather.create(question: "Would you rather not hear or not see?")
WouldYouRather.create(question: "Would you rather eliminate hunger and disease or be able to bring lasting world peace?")
WouldYouRather.create(question: "Would you rather be stranded on a deserted island alone or with someone you don’t like?")
WouldYouRather.create(question: "Would you rather see the future or change the past?")
WouldYouRather.create(question: "Would you rather be three inches taller or three inches shorter?")
WouldYouRather.create(question: "Would you rather wrestle a lion or fight a shark?")
WouldYouRather.create(question: "Would you rather live under water and swim with the fish, or be able to travel through space and touch the stars?")
WouldYouRather.create(question: "Would you rather have magical powers to save the world, or be the strongest person in the world?")
WouldYouRather.create(question: "Would you rather have a dinosaur or a blue whale for a pet?")
WouldYouRather.create(question: "Would you rather be blind or deaf?")
WouldYouRather.create(question: "Would you rather have 500 spiders crawling in your house or 1000 crickets jumping around your room?")
WouldYouRather.create(question: "Would you rather drink a glass full of liquid soap or eat 2 spoons of soap?")
WouldYouRather.create(question: "Would you rather wot watch television or not eat fast food for a month?")
WouldYouRather.create(question: "Would you rather attend school at Hogwarts or live in Narnia?")
WouldYouRather.create(question: "Would you rather have many acquaintances and no friends, or have only one or two close friends?")
WouldYouRather.create(question: "Would you rather win a million dollars in lottery or never have to pay for anything ever again?")
WouldYouRather.create(question: "Would you rather fly all over the world with your favorite celebrity or be stuck on an island with the one you love?")
WouldYouRather.create(question: "Would you rather become a popular celebrity whom everyone hates or be a normal person whom everyone loves?")
WouldYouRather.create(question: "Would you rather go about your normal day naked or have smelly breath and body odor for the whole day?")
WouldYouRather.create(question: "Would you rather kiss a jellyfish or step on a crab?")
WouldYouRather.create(question: "Would you rather have a beautiful house and an ugly car or an ugly house and a beautiful car?")
WouldYouRather.create(question: "Would you rather age from the neck up only or the neck down only?")
WouldYouRather.create(question: "Would you rather eat anything and never get fat or read people’s mind?")
WouldYouRather.create(question: "Would you rather do 10,000 jumping jacks without a break or do 2,000 sit-ups without a break")
WouldYouRather.create(question: "Would you rather would you rather always be 10 minutes late or always be 20 minutes early?")
WouldYouRather.create(question: "Would you rather lose all of your money and valuables or all of the pictures you have ever taken?")
WouldYouRather.create(question: "Would you rather your shirts be always two sizes too big or one size too small?")
WouldYouRather.create(question: "Would you rather live in the wilderness far from civilization or live on the streets of a city as a homeless person?")
WouldYouRather.create(question: "Would you rather live your entire life in a virtual reality where all your wishes are granted or in the real world?")
WouldYouRather.create(question: "Would you rather be alone for the rest of your life or always be surrounded by annoying people?")
WouldYouRather.create(question: "Would you rather never use social media sites / apps again or never watch another movie or TV show?")
WouldYouRather.create(question: "Would you rather have an easy job working for someone else or work for yourself but work incredibly hard?")
WouldYouRather.create(question: "Would you rather be the first person to explore a planet or be the inventor of a drug that cures a deadly disease?")
WouldYouRather.create(question: "Would you rather have a horrible short term memory or a horrible long term memory?")
WouldYouRather.create(question: "Would you rather be locked in a room that is constantly dark for a week or a room that is constantly bright for a week?")
WouldYouRather.create(question: "Would you rather live without the internet or live without AC and heating?")
WouldYouRather.create(question: "Would you rather have a horrible job, but be able to retire comfortably in 10 years or have your dream job, but have to work until the day you die?")
WouldYouRather.create(question: "Would you rather be able to control fire or water?")
WouldYouRather.create(question: "Would you rather have hands that kept growing as you got older or feet that kept growing as you got older?")
WouldYouRather.create(question: "Would you rather unlimited sushi for life or unlimited tacos for life?")
WouldYouRather.create(question: "Would you rather donate your body to science or donate your organs to people who need them?")
WouldYouRather.create(question: "Would you rather never have to work again or never have to sleep again?")
WouldYouRather.create(question: "Would you rather get one free round trip international plane ticket every year or be able to fly domestic anytime for free?")
WouldYouRather.create(question: "Would you rather be fluent in all languages and never be able to travel or be able to travel anywhere for a year but never be able to learn a word of a different language?")
WouldYouRather.create(question: "Would you rather have an unlimited international first class ticket or never have to pay for food at restaurants?")
WouldYouRather.create(question: "Would you rather only eat meat, or only eat vegetables?")
WouldYouRather.create(question: "Would you rather super sensitive taste or super sensitive hearing?")
WouldYouRather.create(question: "Would you rather be able to type fast, or read fast?")
WouldYouRather.create(question: "Would you rather have constantly dry eyes or a constant runny nose?")
WouldYouRather.create(question: "Would you rather be a famous director or a famous actor?")
WouldYouRather.create(question: "Would you rather be constantly tired no matter how much you sleep or constantly hungry no matter what you eat? ")
WouldYouRather.create(question: "Would you rather have a completely automated home or a self-driving car?")
WouldYouRather.create(question: "Would you rather be reincarnated as a fly or just cease to exist after you die?")
WouldYouRather.create(question: "Would you rather be an amazing painter or a brilliant mathematician?")
WouldYouRather.create(question: "Would you rather never lose your phone again or never lose your keys again?")
WouldYouRather.create(question: "Would you rather never get angry or never be envious?")
WouldYouRather.create(question: "Would you rather have free Wi-Fi wherever you go or be able to drink unlimited free coffee at any coffee shop?")
WouldYouRather.create(question: "Would you rather lose your left hand or right foot?")
WouldYouRather.create(question: "Would you rather have a flying carpet or a car that can drive underwater?")
WouldYouRather.create(question: "Would you rather find five dollars on the ground or find all of your missing socks?")
WouldYouRather.create(question: "Would you rather never be stuck in traffic again or never get another cold?")
WouldYouRather.create(question: "Would you rather have a bottomless glass of wine or a bottomless gas tank?")
WouldYouRather.create(question: "Would you rather go bald or always have terrible haircuts?")
WouldYouRather.create(question: "Would you rather have no fingers or no elbows?")
WouldYouRather.create(question: "Would you rather be forced to eat only spicy food or only really bland food?")






